using System.ComponentModel.DataAnnotations;

namespace TextToSqlApi.Models.Requests;

/// <summary>
/// Request body for the <c>POST api/query</c> endpoint.
/// Carries the user's natural-language question and optional configuration hints.
/// </summary>
public sealed class QueryRequest
{
    /// <summary>
    /// The natural-language question to answer using the database.
    /// </summary>
    /// <example>Show me the top 10 customers by revenue in the last quarter.</example>
    [Required(AllowEmptyStrings = false, ErrorMessage = "A question is required.")]
    [StringLength(2000, MinimumLength = 5, ErrorMessage = "Question must be between 5 and 2000 characters.")]
    public string Question { get; init; } = string.Empty;

    /// <summary>
    /// Optional SQL dialect hint (e.g., T-SQL, PostgreSQL, MySQL).
    /// When omitted the service defaults to T-SQL.
    /// </summary>
    /// <example>T-SQL</example>
    public string? SqlDialect { get; init; }

    /// <summary>
    /// Optional maximum number of rows the generated SQL should return.
    /// When omitted a server-side default (typically 100) applies.
    /// </summary>
    /// <example>50</example>
    [Range(1, 5000, ErrorMessage = "MaxRows must be between 1 and 5000.")]
    public int? MaxRows { get; init; }

    /// <summary>
    /// Caller-supplied correlation ID for distributed tracing.
    /// A new GUID is generated by the server when this is omitted.
    /// </summary>
    public string? CorrelationId { get; init; }
}
