namespace TextToSqlApi.Models.Responses;

/// <summary>
/// Response envelope returned by the <c>POST api/query</c> endpoint.
/// Aggregates the generated SQL, raw data, and a business-friendly summary.
/// </summary>
public sealed class QueryResponse
{
    /// <summary>
    /// The original natural-language question echoed back for traceability.
    /// </summary>
    public string Question { get; init; } = string.Empty;

    /// <summary>
    /// The SQL SELECT statement that was generated from the question and
    /// executed against the database.
    /// </summary>
    public string SqlQuery { get; init; } = string.Empty;

    /// <summary>
    /// A business-friendly, plain-English summary of the query results,
    /// generated by the AI model.
    /// </summary>
    public string Summary { get; init; } = string.Empty;

    /// <summary>
    /// The raw query result rows as a collection of dynamic objects.
    /// Each element represents one database row with named properties
    /// corresponding to the column names returned by the query.
    /// </summary>
    public IReadOnlyList<dynamic> Data { get; init; } = [];

    /// <summary>
    /// Total number of rows returned by the query.
    /// </summary>
    public int RowCount { get; init; }

    /// <summary>
    /// Correlation ID for distributed tracing, echoed from the request
    /// or generated by the server when not supplied by the caller.
    /// </summary>
    public string CorrelationId { get; init; } = string.Empty;

    /// <summary>
    /// UTC timestamp when this response was produced.
    /// </summary>
    public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;
}
